version: "3.8"
services:
  server:
    container_name: Fuchsia-server
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - 8080
    environment:
      - PORT=5000
      - NODE_ENV=development
    ports:
      - 5000:5000
    volumes:
      - ./server/src:/app/server/src
    command: npm run dev
    restart: always

  client:
    container_name: Fuchsia-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev-stage
    environment:
      - NODE_ENV=development
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    command: npm run start
    restart: always
