version: "3.8"
services:
  ##########################
  ### SETUP SERVER CONTAINER
  ##########################
  server:
    container_name: Fuchsia-server
    # Tell docker what file to build the server from
    build:
      context: ./server
      dockerfile: Dockerfile
    # The ports to expose
    expose:
      - 8080
    # Environment variables
    environment:
      - PORT=5000
      - NODE_ENV=development
    # Port mapping
    ports:
      - 5000:5000
    # Volumes to mount
    volumes:
      - ./server/src:/app/server/src
    # Run command

    command: npm run dev
    # Restart action
    restart: always
  ##########################
  ### SETUP CLIENT CONTAINER
  ##########################
  client:
    container_name: Fuchsia-client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    expose:
      - 8080
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public

    command: npm run serve
    restart: always
