name: Automated Tests and Linting Back-end

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install packages
        run: npm install
